/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface VerifiableRandomnessOrgInterface extends ethers.utils.Interface {
  functions: {
    "getRandomNumber(uint256)": FunctionFragment;
    "rawFulfillRandomness(bytes32,uint256)": FunctionFragment;
    "s_requestIdToRNG(bytes32)": FunctionFragment;
    "s_requestIdToRange(bytes32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getRandomNumber",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rawFulfillRandomness",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "s_requestIdToRNG",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "s_requestIdToRange",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "getRandomNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rawFulfillRandomness",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "s_requestIdToRNG",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "s_requestIdToRange",
    data: BytesLike
  ): Result;

  events: {
    "RandomnessFulfilled(bytes32,uint256)": EventFragment;
    "RequestedRandomness(bytes32,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "RandomnessFulfilled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RequestedRandomness"): EventFragment;
}

export type RandomnessFulfilledEvent = TypedEvent<
  [string, BigNumber] & { requestId: string; randomness: BigNumber }
>;

export type RequestedRandomnessEvent = TypedEvent<
  [string, BigNumber] & { requestId: string; range: BigNumber }
>;

export class VerifiableRandomnessOrg extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: VerifiableRandomnessOrgInterface;

  functions: {
    getRandomNumber(
      range: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    rawFulfillRandomness(
      requestId: BytesLike,
      randomness: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    s_requestIdToRNG(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    s_requestIdToRange(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  getRandomNumber(
    range: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  rawFulfillRandomness(
    requestId: BytesLike,
    randomness: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  s_requestIdToRNG(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  s_requestIdToRange(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    getRandomNumber(
      range: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    rawFulfillRandomness(
      requestId: BytesLike,
      randomness: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    s_requestIdToRNG(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    s_requestIdToRange(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    "RandomnessFulfilled(bytes32,uint256)"(
      requestId?: BytesLike | null,
      randomness?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { requestId: string; randomness: BigNumber }
    >;

    RandomnessFulfilled(
      requestId?: BytesLike | null,
      randomness?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { requestId: string; randomness: BigNumber }
    >;

    "RequestedRandomness(bytes32,uint256)"(
      requestId?: BytesLike | null,
      range?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { requestId: string; range: BigNumber }
    >;

    RequestedRandomness(
      requestId?: BytesLike | null,
      range?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { requestId: string; range: BigNumber }
    >;
  };

  estimateGas: {
    getRandomNumber(
      range: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    rawFulfillRandomness(
      requestId: BytesLike,
      randomness: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    s_requestIdToRNG(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    s_requestIdToRange(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getRandomNumber(
      range: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    rawFulfillRandomness(
      requestId: BytesLike,
      randomness: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    s_requestIdToRNG(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    s_requestIdToRange(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
